version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins
    build:
      context: jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins/data:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net

networks:
  net: