FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1


COPY ./build_be_product/src /app

COPY ./build_be_product/tests/ /app/tests

WORKDIR /app

ARG DEV=false

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
 


ENV PATH="/py/bin:$PATH"

