FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1


COPY ./build_be_product/src /app

COPY ./build_be_product/tests/ /app/tests

WORKDIR /app

ARG DEV=false

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    if [ $DEV = "true" ]; \
    then /py/bin/pip install -r /tmp/requirements_dev.txt ; \
    fi && \
    rm -rf /tmp

ENV PATH="/py/bin:$PATH"

